kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cloud-cluster
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 31000
      hostPort: 80
      protocol: tcp
- role: worker
