apiVersion: apps/v1
kind: Deployment
metadata:
  name: iweblens
  labels:
    app: iweblens
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iweblens
  template:
    metadata:
      labels:
        app: iweblens
    spec:
      containers:
      - name: iweblens
        image: 31213294/finalcloud

        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"
        ports:
        - containerPort: 5000