apiVersion: v1
kind: Service
metadata:
 name: cloud-service
 labels:
   app: iweblens
spec:
  type: LoadBalancer
  selector:
    app: iweblens
  #type: NodePort
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 5000

